# fly.toml app configuration file generated for apirecipe on 2023-07-15T12:01:53-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apirecipe"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
